#!/bin/bash

EXEC=./bin/test
SIMULATOR=simulavr
TERMINAL=guake
MCU=atmega324a
F_CPU=8000000


if [ ${SIMULATOR} == "simavr" ]
then
    echo "simavr not supported"
    exit 1

elif [ ${SIMULATOR} == "simulavr" ]
then
    OPTS="--writetopipe 0xC6,dump --gdb-debug --device ${MCU} --cpufrequency ${F_CPU} -V --file ${EXEC}"
else
    echo "Simulator ${SIMULATOR} is not supported"
    exit 1
fi


if [ $TERMINAL == "gnome-terminal" ]
then
    CMD="${TERMINAL} -- ${SIMULATOR} ${OPTS}"
elif [ $TERMINAL == "konsole" ]
then
    CMD="${TERMINAL} --workdir ${PWD} --seperate -e ${SIMULATOR} ${OPTS} &"
elif [ $TERMINAL == "urxvt" ]
then
    CMD="${TERMINAL} -e ${SIMULATOR} ${OPTS} &"
elif [ $TERMINAL == "guake" ]
then
    CMD="${SIMULATOR} ${OPTS} &"
else
    echo "Terminal ${TERMINAL} is not supported"
    exit 1
fi

${CMD}
#avr-gdb -x .gdbinit ${EXEC}
#pkill ${SIMULATOR}
