/*
 * Copyright (C) Olivier Dion <olivier.dion@polymtl.ca>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include "YAROS/def.h"
#include "YAROS/global.h"
#include "YAROS/sched.h"
#include "YAROS/sysclk.h"
#include "YAROS/msg.h"

#include "devices/clk.h"
#include "devices/irq.h"

#include <stddef.h>

/*
  The Atmega324PA has a CPU frequency of 8 MHz. The following table
  describe the incidence of the system clock frequency (HZ) on the system.

  The system clock is generated by using the TIMER0_OVF_vect interrupt.

  Here's a description of the different fields.

  *HZ*
  The system clock frequency.

  *Jiffy*
  The smallest unit of time of the system clock.

  *Timer Scale*
  The prescaler needed on the timer to generate the desired HZ.

  *Count*
  Every time the interrupt occured, it's necessary to put in TCNT0 the
  value 0xFF - count.

  *Latency*
  The inverse of the fractional part of *count*. We add one to TCNT0
  every *L* interrupt.

  *Days*
  The number of days before the jiffies counter overflow (32 bits).

  *Work*
  The percentage of work done in the interrupt routine for every jiffy.

  |------+------------+-------------+-------+---------+----------------+----------|
  |   HZ | Jiffy (ms) | Timer Scale | Count | Latency | Days (32 bits) | Work (%) |
  |------+------------+-------------+-------+---------+----------------+----------|
  |   50 |         20 |        1024 |   100 |       4 |            994 |   0.0316 |
  |  100 |         10 |        1024 |   178 |       8 |            497 |   0.0629 |
  |  125 |          8 |         256 |     6 |       0 |            397 |   0.0703 |
  |  200 |          5 |        1024 |   217 |      16 |            248 |   0.1255 |
  |  250 |          4 |         256 |   131 |       0 |            198 |   0.1406 |
  |  500 |          2 |          64 |     6 |       0 |             99 |   0.2813 |
  | 1000 |          1 |          64 |   131 |       0 |             49 |   0.5625 |
  |------+------------+-------------+-------+---------+----------------+----------|
*/

/* For 8Mhz. TODO: Make this good for every frequency */
#if HZ == 50
# define KCLK_SRC CLK_P1024
# define KCLK_SCALE 1024
# define KCLK_COUNT 100
# define KCLK_LATENCY 4

#elif HZ == 100
# define KCLK_SRC CLK_P1024
# define KCLK_SCALE 1024
# define KCLK_COUNT 178
# define KCLK_LATENCY 8

#elif HZ == 125
# define KCLK_SRC CLK_P256
# define KCLK_SCALE 256
# define KCLK_COUNT 6
# define KCLK_LATENCY 0

#elif HZ == 200
# define KCLK_SRC CLK_P1024
# define KCLK_SCALE 1024
# define KCLK_COUNT 217
# define KCLK_LATENCY 16

#elif HZ == 250
# define KCLK_SRC CLK_P256
# define KCLK_SCALE 256
# define KCLK_COUNT 131
# define KCLK_LATENCY 0

#elif HZ == 500
# define KCLK_SRC CLK_P64
# define KCLK_SCALE 64
# define KCLK_COUNT 6
# define KCLK_LATENCY 0

#elif HZ == 1000
# define KCLK_SRC CLK_P64
# define KCLK_SCALE 64
# define KCLK_COUNT 131
# define KCLK_LATENCY 0

#else
#  error HZ value not supported.
#endif


/*
 * Save on Stack r24, r25, SREG
 */
#define save_minimal_context() \
    asm volatile ("push r24\n\t" \
                  "push r25\n\t" \
                  "in r24, __SREG__\n\t"       \
                  "push r24\n\t" \
                  )

#define restore_minimal_context() \
    asm volatile ("pop r24\n\t" \
                  "out __SREG__, r24\n\t"      \
                  "pop r25\n\t" \
                  "pop r24\n\t" \
                  )

INLINE void
increment_jiffies()
{
    asm volatile (
        /*
         * We need to to adjust the initial value of TCNT0 with the
         * 7 previous cycles and the next 2.
         */
        "ldi r24, " xstr(KCLK_COUNT + (9 / KCLK_SCALE)) "\n\t"
        "out 0x26, r24\n\t"

        /* Load jiffies lower 16 bits */
        "lds r24, jiffies\n\t"
        "lds r25, jiffies+1\n\t"

        /* ++jiffies */
        "adiw r24, 1\n\t"
        "sts jiffies, r24\n\t"
        "sts jiffies+1, r25\n\t"
        "lds r24, jiffies+2\n\t"
        "adc r24, r1\n\t"
        "sts jiffies+2, r24\n\t"
        "lds r24, jiffies+3\n\t"
        "adc r24, r1\n\t"
        "sts jiffies+3, r24\n\t"

#  if KCLK_LATENCY != 0

        /*
         * If the timer as a latency because of HZ, we have to
         * increment TCNT0 every KCLK_LATENCY interrupts. See the
         * table in clock.h
         */

        /* Load jiffies in r24 */
        "lds r24, jiffies\n\t"


        /* if (jiffies % KCLK_LATENCY == 0) */
        /* BRANCH .restore if != 0 */
        "andi r24, " xstr(KCLK_LATENCY - 1) "\n\t"
        "brne .restore\n\t"

        /* ++TCNT0 */
        "in r24, 0x26\n\t"
#  if KCLK_SCALE <= 29        /* Same reason has before */
        "subi r24, lo8(-(2))\n\t"
#  else
        "subi r24, lo8(-(1))\n\t"
#  endif
        "out 0x26, r24\n"


#  endif    /* KCLK_LATENCY */
        ".restore:\n\t"
        //  "ret"
        );
}

/**
 * @file sysclkc.c
 *
 * @brief System Clock for the ATmega324PA.
 *
 * An optimization could be made. Instead of using the timer overflow
 * vector, it would be possible to use one of the compare units
 * (KCLK_COMPA_vect or KCLK_COMPB_vect) and put the timer in CTC
 * mode. This would save the 2 instructions of reseting the TCNT to
 * the appropriate value, because the hardware will do it for
 * us. Therefore, it would be possible to save 2 cycles and 4 bytes of
 * memory.
 *
 * However, I'll rather use the timer overflow instead, leaving the
 * two compare units free for something else.
 */
ISR(KCLK_vect, ISR_NAKED)
{
    /*
     * Minimal context is r25, r24 and SREG. Therefore, everything has
     * to be done with those 3 registers until the minimal context is
     * restored.
     */
    save_minimal_context();

    increment_jiffies();

    /*
     * r24 <-time_slice
     *
     * r24 != 0 -> skip_schedule
     * r24 == 0 -> schedule
     */
    asm volatile ("lds r24, time_slice\n\t"
                  "cpi r24, 0\n\t"
                  "breq .schedule\n\t"
                  "jmp .skip_schedule\n"); /* Skip scheduling */

    asm volatile(".schedule:\n");

    restore_minimal_context();

    do_schedule();

    reti();

    /* If not scheduling, decrement time_slice */
    asm volatile (".skip_schedule:\n\t"
                  "subi r24, 1\n\t"
                  "sts time_slice, r24\n\t");

    restore_minimal_context();

    reti();
}

/**
 * @brief Initialize the System Clock.
 *
 * This routine will initialize the Kernel clock to the desired
 * frequency.
 */
void
kinit_sysclk(void)
{
    if (init_clk(KCLK,
                 CLK_NORMAL,
                 KCLK_SRC,
                 0) != OK) {
        FATAL("kinit_sysclk");
    }
}
